# Generated by Django 6.1.1 on 2026-09-14 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NEW_RELEVANT_JOB', 'New relevant job'), ('NEW_APPLICATION', 'Someone applied'), ('APPLICATION_ACCEPTED', 'Application accepted'), ('APPLICATION_REJECTED', 'Application rejected'), ('JOB_STARTED', 'Job starting'), ('JOB_MARKED_COMPLETE', 'Worker marked job complete'), ('COMPLETION_CONFIRMED', 'Completion confirmed'), ('PAYMENT_SENT', 'Payment marked sent'), ('PAYMENT_CONFIRMED', 'Payment confirmed'), ('NEW_REVIEW', 'New review'), ('JOB_CANCELLED', 'Job cancelled')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(blank=True, max_length=500)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
