# Generated by Django 6.1.1 on 2026-09-22 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estates', '0003_estate_daily_gate_code_estate_gate_code_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='0 for free giveaways', max_digits=10)),
                ('condition', models.CharField(choices=[('NEW', 'Brand New'), ('LIKE_NEW', 'Like New'), ('USED', 'Fairly Used')], default='USED', max_length=15)),
                ('category', models.CharField(choices=[('FURNITURE', 'Furniture & Home'), ('ELECTRONICS', 'Electronics & Appliances'), ('FOOD_GROCERIES', 'Food & Homemade Items'), ('KIDS_BABY', 'Kids & Baby'), ('GIVEAWAY', 'Free / Giveaway'), ('OTHER', 'Other Items')], default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold')], default='AVAILABLE', max_length=15)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='classified_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classified_items', to='estates.estate')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classified_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ANNOUNCEMENT', 'Official Announcement'), ('LOST_FOUND', 'Lost & Found'), ('RECOMMENDATION', 'Recommendation'), ('EVENT', 'Estate Event'), ('NOTICE', 'Community Notice'), ('GENERAL', 'General Post')], default='GENERAL', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='feed_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_posts', to=settings.AUTH_USER_MODEL)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_posts', to='estates.estate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
