# Generated by Django 6.1.1 on 2026-09-22 16:28

import apps.gate.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estates', '0003_estate_daily_gate_code_estate_gate_code_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='e.g. Chowdeck, Uber, Jumia, Logistics', max_length=100)),
                ('rider_name', models.CharField(blank=True, max_length=150)),
                ('rider_phone', models.CharField(blank=True, max_length=30)),
                ('pass_code', models.CharField(default=apps.gate.models.generate_pass_code, max_length=20, unique=True)),
                ('package_details', models.CharField(blank=True, help_text='e.g. Food order, Electronics package', max_length=255)),
                ('status', models.CharField(choices=[('EXPECTED', 'Rider Expected'), ('ARRIVED', 'Arrived at Gate'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='EXPECTED', max_length=15)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_passes', to='estates.estate')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_passes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('VISITOR_ISSUE', 'Visitor Issue'), ('GATE_PROBLEM', 'Gate Problem / Congestion'), ('DELIVERY_ARRIVED', 'Delivery Arrived'), ('EMERGENCY_SOS', 'Emergency SOS'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity')], max_length=25)),
                ('description', models.TextField()),
                ('unit_location', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACKNOWLEDGED', 'Acknowledged by Gate'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_alerts', to='estates.estate')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=150)),
                ('visitor_phone', models.CharField(blank=True, max_length=30)),
                ('pass_code', models.CharField(default=apps.gate.models.generate_pass_code, max_length=20, unique=True)),
                ('expected_date', models.DateField()),
                ('expected_time', models.TimeField(blank=True, null=True)),
                ('vehicle_number', models.CharField(blank=True, help_text='Car license plate e.g. KJA-123AA', max_length=50)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Entry'), ('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=15)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_passes', to='estates.estate')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_passes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
