# Generated by Django 6.1.1 on 2026-10-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('RESIDENT', 'Estate Resident'), ('GATE_SECURITY', 'Gate Security / Gateman'), ('ESTATE_ADMIN', 'Estate Administrator')], default='RESIDENT', max_length=25),
        ),
    ]
