# Generated by Django 6.1.1 on 2026-10-03 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0004_estatelevy_paymentreceipt'),
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING_AUDIT', 'Pending Household Audit'), ('PENDING_APPROVAL', 'Pending Admin Approval'), ('PENDING_VERIFICATION', 'Pending verification'), ('VERIFIED', 'Verified'), ('SUSPENDED', 'Suspended'), ('BANNED', 'Banned')], default='UNVERIFIED', max_length=25),
        ),
        migrations.CreateModel(
            name='HouseholdAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_address', models.CharField(help_text='e.g. Block 4, House 12', max_length=150)),
                ('occupant_type', models.CharField(choices=[('OWNER', 'Home Owner'), ('TENANT', 'Tenant / Renter')], default='TENANT', max_length=15)),
                ('occupant_count', models.PositiveIntegerField(default=1)),
                ('next_of_kin_name', models.CharField(max_length=150)),
                ('next_of_kin_relationship', models.CharField(help_text='e.g. Spouse, Parent, Sibling', max_length=50)),
                ('next_of_kin_phone', models.CharField(max_length=30)),
                ('vehicle_plates', models.CharField(blank=True, help_text='Car plate numbers separated by commas', max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_audits', to='estates.estate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='household_audit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
