# Generated by Django 6.1.1 on 2026-10-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_status_householdaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('RESIDENT', 'Estate Resident'), ('GATE_SECURITY', 'Estate Security Officer'), ('ESTATE_ADMIN', 'Estate Administrator')], default='RESIDENT', max_length=25),
        ),
    ]
