import uuid
from django.conf import settings
from django.db import models


def generate_pass_code():
    return f"PASS-{uuid.uuid4().hex[:6].upper()}"


class VisitorPass(models.Model):
    """Visitor access pass generated by a resident for entry clearance at the estate gate."""

    class Status(models.TextChoices):
        PENDING = "PENDING", "Pending Entry"
        CHECKED_IN = "CHECKED_IN", "Checked In"
        CHECKED_OUT = "CHECKED_OUT", "Checked Out"
        CANCELLED = "CANCELLED", "Cancelled"
        EXPIRED = "EXPIRED", "Expired"

    resident = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="visitor_passes"
    )
    estate = models.ForeignKey("estates.Estate", on_delete=models.CASCADE, related_name="visitor_passes")
    visitor_name = models.CharField(max_length=150)
    visitor_phone = models.CharField(max_length=30, blank=True)
    pass_code = models.CharField(max_length=20, unique=True, default=generate_pass_code)
    expected_date = models.DateField()
    expected_time = models.TimeField(blank=True, null=True)
    vehicle_number = models.CharField(max_length=50, blank=True, help_text="Car license plate e.g. KJA-123AA")
    notes = models.CharField(max_length=255, blank=True)
    status = models.CharField(max_length=15, choices=Status.choices, default=Status.PENDING)
    checked_in_at = models.DateTimeField(blank=True, null=True)
    checked_out_at = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.visitor_name} ({self.pass_code}) - {self.status}"


class DeliveryPass(models.Model):
    """Pre-cleared rider or package delivery (Uber Eats, Chowdeck, Jumia, DHL, etc.)"""

    class Status(models.TextChoices):
        EXPECTED = "EXPECTED", "Rider Expected"
        ARRIVED = "ARRIVED", "Arrived at Gate"
        COMPLETED = "COMPLETED", "Completed"
        CANCELLED = "CANCELLED", "Cancelled"

    resident = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="delivery_passes"
    )
    estate = models.ForeignKey("estates.Estate", on_delete=models.CASCADE, related_name="delivery_passes")
    company_name = models.CharField(max_length=100, help_text="e.g. Chowdeck, Uber, Jumia, Logistics")
    rider_name = models.CharField(max_length=150, blank=True)
    rider_phone = models.CharField(max_length=30, blank=True)
    pass_code = models.CharField(max_length=20, unique=True, default=generate_pass_code)
    package_details = models.CharField(max_length=255, blank=True, help_text="e.g. Food order, Electronics package")
    status = models.CharField(max_length=15, choices=Status.choices, default=Status.EXPECTED)
    arrived_at = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"[{self.company_name}] {self.rider_name or 'Rider'} ({self.status})"


class SecurityAlert(models.Model):
    """Structured security logs & resident alerts (Incident, Gate issue, SOS)."""

    class AlertType(models.TextChoices):
        VISITOR_ISSUE = "VISITOR_ISSUE", "Visitor Issue"
        GATE_PROBLEM = "GATE_PROBLEM", "Gate Problem / Congestion"
        DELIVERY_ARRIVED = "DELIVERY_ARRIVED", "Delivery Arrived"
        EMERGENCY_SOS = "EMERGENCY_SOS", "Emergency SOS"
        SUSPICIOUS_ACTIVITY = "SUSPICIOUS_ACTIVITY", "Suspicious Activity"

    class Status(models.TextChoices):
        PENDING = "PENDING", "Pending"
        ACKNOWLEDGED = "ACKNOWLEDGED", "Acknowledged by Gate"
        RESOLVED = "RESOLVED", "Resolved"

    reporter = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="security_alerts"
    )
    estate = models.ForeignKey("estates.Estate", on_delete=models.CASCADE, related_name="security_alerts")
    alert_type = models.CharField(max_length=25, choices=AlertType.choices)
    description = models.TextField()
    unit_location = models.CharField(max_length=150, blank=True)
    status = models.CharField(max_length=15, choices=Status.choices, default=Status.PENDING)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.alert_type} by {self.reporter} ({self.status})"
