# Generated by Django 6.1.1 on 2026-09-22 16:15

import apps.estates.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='daily_gate_code',
            field=models.CharField(default=apps.estates.models.generate_gate_code, max_length=20),
        ),
        migrations.AddField(
            model_name='estate',
            name='gate_code_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='estate',
            name='rules_document',
            field=models.TextField(blank=True, help_text='Estate rules, guidelines, and notices'),
        ),
        migrations.AddField(
            model_name='estatemembership',
            name='unit_address',
            field=models.CharField(blank=True, help_text='House / Flat / House number', max_length=150),
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_gate_desk', models.BooleanField(default=False)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='estates.estate')),
            ],
            options={
                'ordering': ['-is_gate_desk', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('WATER', 'Water / Plumbing'), ('POWER', 'Power / Electrical'), ('GATE', 'Gate / Access'), ('SECURITY', 'Security Concern'), ('INFRASTRUCTURE', 'Roads / Infrastructure'), ('OTHER', 'Other Complaint')], default='OTHER', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, help_text='Block / House number affected', max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tickets', to='estates.estate')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
