# Generated by Django 6.1.1 on 2026-10-03 12:42

import apps.estates.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0003_estate_daily_gate_code_estate_gate_code_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstateLevy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. October 2026 Security & Facility Maintenance Levy', max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=15000.0, max_digits=10)),
                ('month_year', models.CharField(help_text='e.g. OCTOBER 2026', max_length=30)),
                ('due_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levies', to='estates.estate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_address', models.CharField(max_length=150)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(default=apps.estates.models.generate_receipt_ref, max_length=50, unique=True)),
                ('payment_method', models.CharField(choices=[('PAYSTACK', 'Paystack Online'), ('SIMULATED_TEST', 'Test Simulation Mode'), ('BANK_TRANSFER', 'Bank Transfer')], default='SIMULATED_TEST', max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success / Paid'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], default='SUCCESS', max_length=15)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='estates.estate')),
                ('levy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='estates.estatelevy')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_at'],
                'unique_together': {('levy', 'resident')},
            },
        ),
    ]
