# Generated by Django 6.1.1 on 2026-09-22 16:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estates', '0003_estate_daily_gate_code_estate_gate_code_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Business Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('tagline', models.CharField(blank=True, help_text='e.g. Fast & Reliable Electrical Fixes', max_length=255)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('address_or_unit', models.CharField(blank=True, help_text='e.g. Block 2, Shop 4 or Resident Unit', max_length=255)),
                ('opening_hours', models.CharField(blank=True, help_text='e.g. Mon-Sat: 8:00 AM - 7:00 PM', max_length=100)),
                ('is_promoted', models.BooleanField(default=False, help_text='Promoted featured ad flag')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='business_photos/')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='businesses.businesscategory')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_profiles', to='estates.estate')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_promoted', '-average_rating', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_inquiries', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='businesses.businessprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='businesses.businessprofile')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('business', 'reviewer')},
            },
        ),
    ]
